### ISSUE TITLE
exec failed: permission denied

### ISSUE THREAD

**Issue by saz59** [bofm/docker-oracle12c#1]
After make all

> root@hadoop:/exch/docker-oracle12c-master# make run
> error: exec failed: permission denied
> 
> root@hadoop:/exch/docker-oracle12c-master# make run-priv
> docker run -it --rm -v /data --privileged  --name oracle bofm/oracle12c bash --shm
> Mounting /dev/shm...
> error: exec failed: permission denied
> Makefile:49: recipe for target 'run-priv' failed
> make: **\* [run-priv] Error 1

**Comment by bofm** [comment]
What is the OS on the host? What's the version of Docker?
Try this:

```
docker run -it --rm --privileged --entrypoint="bash"  --name oracle bofm/oracle12c
# then in the container
entrypoint.sh --shm bash
```

**Comment by saz59** [comment]
root@hadoop:/exch/docker-oracle12c-master# docker run -it --rm --privileged --entrypoint="bash" --name oracle bofm/oracle12c entrypoint.sh --shm bash
Mounting /dev/shm...
error: exec failed: permission denied

root@hadoop:/exch/docker-oracle12c-master# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
DISTRIB_CODENAME=utopic
DISTRIB_DESCRIPTION="Ubuntu 14.10"
NAME="Ubuntu"
VERSION="14.10 (Utopic Unicorn)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.10"
VERSION_ID="14.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

root@hadoop:/exch/docker-oracle12c-master# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

root@hadoop:/exch/docker-oracle12c-master# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
root@hadoop:/exch/docker-oracle12c-master# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

###########Dockerfile################
#FROM oraclelinux
FROM tvierling/oraclelinux:7

Reason: oraclelinux -  Error unpacking rpm package systemd-208-20.0.1.el7_1.2.x86_64

**Comment by bofm** [comment]
"entrypoint.sh --shm bash" should have been run inside the container

**Comment by bofm** [comment]
Base image was changed. This issue is not related to the current project.
