### ISSUE TITLE
dbca_log: ORA-00845: MEMORY_TARGET not supported on this system

### ISSUE THREAD

**Issue by limx59** [bofm/docker-oracle12c#11]
创建完bofm/oracle以后，执行如下：
docker run -t -i --shm-size 2GB borm/oracle 
在创建oracle时，发现执行错误：
dbca_log: ORA-00845: MEMORY_TARGET not supported on this system

**Comment by bofm** [comment]
How much memory do you have on the Docker host?

Also please check out closed issues related to the same problem.

**Comment by bofm** [comment]
Must be fixed in v0.3
