### ISSUE TITLE
do we need to orainstRoot.sh and root.sh script or it is automatic

### ISSUE THREAD

**Issue by vikasgubbi** [bofm/docker-oracle12c#14]
getting below mentioned error message when i try to execute 

root@ubuntu:~# docker exec -it oracle_database gosu oracle sqlplus / as sysdba
error: failed switching to "oracle": operation not permitted

**Comment by bofm** [comment]
Does it work without gosu?

**Comment by bofm** [comment]
So yes, this should work without gosu. Fixed Readme.
