### ISSUE TITLE
Unable to change password for oracle user

### ISSUE THREAD

**Issue by jklepek** [bofm/docker-oracle12c#15]
I need to change the password for oracle user. I log into root user, run the passwd procedure to change password, it says it is successfully updated, but if I try to log into oracle user, it gives me error, like it wasn't changed at all.
I use this image for our developers, it is by far, the best for our needs. If I could change the password it would be perfect.
I assume it is possible by rewriting some line in the build script, but I don't know where to look.
Anyway, great work, thank you!

**Comment by bofm** [comment]
>  I log into root user, run the passwd procedure to change password, it says it is successfully updated, but if I try to log into oracle user, it gives me error, like it wasn't changed at all.

Can you give an example of the commands to reproduce this?

Maybe this could solve your problem: add this line to `step2/Dockerfile`
```Dockerfile
RUN echo 'oracle:new_password' | chpasswd
```
But take into account that storing passwords in a Dockerfile is a bad idea.

Btw, why do you need the password? Is `docker exec` not enough?

Update:
If there are problems with `|` symbol in Dockerfile, then create `myscript.sh` file like this
```bash
#!/usr/bin/env bash

echo 'oracle:new_password' | chpasswd
```
and in step2/Dockerfile add these lines **before the line with** `USER oracle`:
```
COPY myscript.sh /tmp/myscript.sh
RUN /tmp/myscript.sh
```

**Comment by jklepek** [comment]
> Can you give an example of the commands to reproduce 

> 

docker exec -it -u root database_container bash
passswd oracle
password
password
Now it says all tokens updated successfully, but apparently not.

> Btw, why do you need the password? Is docker exec not enough?

Unfortunately not, as we are developing an app, that connects to database instance (container in this case) and it uses it's system authentication.
Thank you, for quick response!
And as I've said, great work 👍 :)

**Comment by jklepek** [comment]
Ok, I've just tried it and there seems to be other problem. The password is changed all right.
But if log into as other user
`docker exec -it -u spadmin container bash` and then try to open session for user oracle `su oracle` and enter password, it gives me error `su: cannot open session: Permission denied`

**Comment by jklepek** [comment]
So, I was able to figure it out. The problem was in security file.
https://susguzman.wordpress.com/2017/06/26/su-cannot-open-session-permission-denied-oracle-database-12c-sobre-docker/
This solved it for me.
Anyway, thanks for your help!
