### ISSUE TITLE
manifest for bofm/oracle12c:installed not found

### ISSUE THREAD

**Issue by itJunky** [bofm/docker-oracle12c#16]
Sending build context to Docker daemon  22.02kB
Step 1/13 : FROM bofm/oracle12c:installed
manifest for bofm/oracle12c:installed not found
******* FAILED 4 times

And failed again and again.

**Comment by bofm** [comment]
Docker version?
What commands do you execute?

**Comment by itJunky** [comment]
Now i'm use this realisation https://github.com/wscherphof/oracle-12c and it's work perfectly!

**Comment by bofm** [comment]
Awesome!
