### ISSUE TITLE
Can you tell me how to change the port of the database?

### ISSUE THREAD

**Issue by imooni** [bofm/docker-oracle12c#18]
Because I want to run two container in docker to test .

**Comment by imooni** [comment]
I can't find the configuration file.

**Comment by bofm** [comment]
You can change port with `-p` parameter of `docker run` command.

**Comment by imooni** [comment]
Misunderstood . The port I am referring to is the oracle database service or the listening port.

**Comment by bofm** [comment]
The configuration is a default configuration created by Oracle DBCA. It might be possible to change the port with the "response file". Not sure at the moment. 

Why do you need to change the port *inside the container*? Are you going to run multiple instances in one container?

**Comment by imooni** [comment]
Thank you for your answer. Well, I want to run two containers on the same server, so I need to modify the port. I've given up modifying ports because I bought another server. It's too much trouble to modify ports.

**Comment by imooni** [comment]
Thank you for your open source, which saves us a lot of time. good luck.

**Comment by bofm** [comment]
You run it with docker. And the ports become available on the host via `docker run -p <host_port>:<container_port>`. Just set different <host_port> for each container.

**Comment by bofm** [comment]
Inside the container the port is defined somewhere in $ORACLE_HOME/network/admin/listener.ora. But, one more time, the project is designed in a way that you would not have to do it.
