### ISSUE TITLE
make: *** [install] Error 127 /bin/bash: ./runInstaller: No such file or directory

### ISSUE THREAD

**Issue by ttw19974** [bofm/docker-oracle12c#5]
I get this error when I run make

$ make all
\033[32mInstalling Oracle Database software...\033[0m
Unable to find image 'bofm/oracle12c:preinstall' locally
preinstall: Pulling from bofm/oracle12c
a3ed95caeb02: Pull complete
4164c8cc49b7: Pull complete
6a54cbaa2f35: Pull complete
a8482cde7cad: Pull complete
80fd503b7647: Pull complete
cf214770b793: Pull complete
0d5d1e8a3a13: Pull complete
d62732ebc72a: Pull complete
07354f4227e1: Pull complete
bab3fa98616c: Pull complete
Digest: sha256:7e8043881e932f40e0b5c916faa5dda121186bc93d653969ff216e46e37a2aa5
Status: Downloaded newer image for bofm/oracle12c:preinstall
/bin/bash: ./runInstaller: No such file or directory
make: **\* [install] Error 127

**Comment by bofm** [comment]
1.  download `linuxamd64_12102_database_1of2.zip` and `linuxamd64_12102_database_2of2.zip` from [oracle.com](http://www.oracle.com/technetwork/database/enterprise-edition/downloads/database12c-linux-download-2240591.html) **and extract the archives to current directory**.
2. Execute the following lines in bash and wait ~15 minutes:

``` shell
git clone https://github.com/bofm/docker-oracle12c.git
cd docker-oracle12c
make all
```
