### ISSUE TITLE
Apex Support, Windows, Persistent DB?

### ISSUE THREAD

**Issue by XeZZoR** [bofm/docker-oracle12c#7]
Hello,

quite new to Docker and I have some Questions/issues here.

I want to use this image on a windows mashine with an APEX application deployed into it. So first I need to install Apex into the image which I kinda don't know how. 

Is it possible to Take the Image, put it on Windows, start it and have a persistent database? What happens if Windows will be shutdown without stopping the image before? Is it possible to add Apex 5 to the image?

**Comment by bofm** [comment]
Windows: You'd better check Docker docs.

APEX: I think you can edit [step2/db_template.dbt](https://github.com/bofm/docker-oracle12c/blob/master/step2/db_template.dbt) to install APEX.
