### ISSUE TITLE
Error to install /bin/bash: ./runInstaller: No such file or directory

### ISSUE THREAD

**Issue by eniomachado** [bofm/docker-oracle12c#8]
enio_oliveira@homeworkte:~/Documents/docker-oracle12c$ make all
Installing Oracle Database software...
c3be46c2902c        bofm/oracle12c:preinstall             "/tmp/install/install"   8 minutes ago       Exited (127) 8 minutes ago                           oracle_install
oracle_install
/bin/bash: ./runInstaller: No such file or directory
Makefile:50: recipe for target 'install' failed
make: **\* [install] Error 127

I1m getting this error when i execute the command line "make all"

**Comment by antonmry** [comment]
Hi @eniomachado 

I've done it right now and installation works well. Do you have the unzipped database folder in ~/Documents/ ?

**Comment by bofm** [comment]
#5

**Comment by bofm** [comment]
#5
