### ISSUE TITLE
Error running the container MEMORY_TARGET not supported on this system

### ISSUE THREAD

**Issue by antonmry** [bofm/docker-oracle12c#9]
When running the container, there is an error:

```
MEMORY_TARGET not supported on this system
```

and the containers exits.  My info:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 257
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-2495626-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.57 GB
 Data Space Total: 107.4 GB
 Data Space Available: 17.74 GB
 Metadata Space Used: 11.38 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.9-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.704 GiB
Name: gali7
ID: 5SH4:FMHV:JZ6W:AKLM:QBAS:LU7R:DHNI:KTFW:TZGX:HQBR:5SY4:JNZO
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by bofm** [comment]
How do you run the container? Did you use `--shm-size` parameter? Oracle AMM requires shared memory to be mounted.

**Comment by antonmry** [comment]
Hi @bofm 

Thanks for the quick response, this is the command I've executed:

```
docker run -d --shm-size 1GB --name oracledb -p 1521:1521 bofm/oracle12c
```

**Comment by bofm** [comment]
Is shared memory mounted on the host?
`mount|grep shm`

If it's not, try this:
`mount -t tmpfs tmpfs /dev/shm -o rw,nosuid,nodev`

**Comment by antonmry** [comment]
Yes, it is:

```
$ mount | grep shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
```

Thanks for your help!

**Comment by bofm** [comment]
Could you please
`docker run --rm --shm-size 1GB bofm/oracle12c bash -c mount | grep -E 'shm|tmpfs'`

**Comment by ashaver** [comment]
I had a very similar error and just had to increase the size of the shared memory. 
Before:
- docker run -d --shm-size 1GB --name oracledb -p 1521:1521 bofm/oracle12c
  After:
- docker run -d --shm-size 4GB --name oracledb -p 1521:1521 bofm/oracle12c

Doing an attach to the running container showed exactly what the problem was:
- docker attach bofm/oracle 12c

**Comment by bofm** [comment]
Exactly! Oracle attempts to use 40% of total memory and fails as there is only 1G available. If you are not planning to use more than 1G then just edit create_database script and set memory percentage according to your requirements.

If there is 8GB of memory on the Docker host and 1GB is planned to be given to Oracle database, then memory percentage should be set to 12 and `--shm-size 1GB` arg should be used when running the container.

**Comment by antonmry** [comment]
Change memory percentage to 12 worked as charm, thanks for the help!
